# Generated by Django 5.0.1 on 2026-02-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='rubric_file',
            field=models.FileField(blank=True, null=True, upload_to='rubrics/'),
        ),
    ]
