# Generated by Django 5.0.1 on 2026-02-14 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_alter_submission_rubric_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='question_text',
            field=models.TextField(blank=True, db_column='question_text'),
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='question_text',
            new_name='_question_text',
        ),
        migrations.AlterField(
            model_name='submission',
            name='rubric_text',
            field=models.TextField(blank=True, db_column='rubric_text'),
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='rubric_text',
            new_name='_rubric_text',
        ),
        migrations.AddField(
            model_name='submission',
            name='student_name',
            field=models.CharField(default='Unknown Student', max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='question_file',
            field=models.FileField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('question_file', models.FileField(upload_to='questions/')),
                ('rubric_file', models.FileField(blank=True, null=True, upload_to='rubrics/')),
                ('question_text', models.TextField(blank=True)),
                ('rubric_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='evaluations.exam'),
        ),
    ]
